package dev.nexvisuals.client.gui;

import com.mojang.blaze3d.platform.InputConstants;
import dev.nexvisuals.client.render.Draw;
import dev.nexvisuals.client.integration.ShaderIntegration;
import dev.nexvisuals.core.config.GlobalSettings;
import dev.nexvisuals.core.config.ProfileManager;
import dev.nexvisuals.core.module.Category;
import dev.nexvisuals.core.module.ModuleRegistry;
import dev.nexvisuals.core.module.VisualModule;
import dev.nexvisuals.core.setting.KeybindSetting;
import dev.nexvisuals.core.setting.Setting;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.AbstractWidget;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.components.Tooltip;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.input.KeyEvent;
import net.minecraft.client.input.MouseButtonEvent;
import net.minecraft.network.chat.Component;
import org.lwjgl.glfw.GLFW;

import java.util.List;
import java.util.function.BooleanSupplier;
import java.util.function.Supplier;

/** Adaptive navigation and composition. Setting controls are generated by SettingControls. */
public final class NexVisualsScreen extends Screen {
    private final Screen parent;
    private final ModuleRegistry registry;
    private final GlobalSettings globals;
    private final Runnable save;
    private final ProfileManager profiles;
    private final GuiState state;
    private GuiLayout layout;
    private ScrollPane categoryPane;
    private ScrollPane modulePane;
    private ScrollPane settingPane;
    private EditBox search;
    private KeybindSetting capturing;
    private boolean rebuildRequested;
    private boolean restoreSearchFocus;
    private final java.util.Map<String, Integer> presetSelections = new java.util.HashMap<>();

    public NexVisualsScreen(Screen parent, ModuleRegistry registry, GlobalSettings globals, Runnable save) {
        this(parent, registry, globals, null, save);
    }

    public NexVisualsScreen(Screen parent, ModuleRegistry registry, GlobalSettings globals,
                           ProfileManager profiles, Runnable save) {
        super(Component.literal("NexVisuals"));
        this.parent = parent;
        this.registry = registry;
        this.globals = globals;
        this.save = save;
        this.profiles = profiles;
        this.state = new GuiState(globals);
    }

    @Override protected void init() {
        layout = GuiLayout.of(width, height, state.narrowDetails);
        categoryPane = null;
        modulePane = null;
        settingPane = null;
        int toolbarX = layout.left() + 8;
        int toolbarY = layout.toolbarY();
        int hudButtonRight = layout.left() + layout.width() - (profiles == null ? 8 : 82);
        NexButton hudEditor = addRenderableWidget(button(hudButtonRight - 62, layout.top() + 9, 62, 21,
                () -> "HUD editor", () -> false, () -> minecraft.setScreen(new HudEditorScreen(this, registry, globals, save)),
                "Drag and align HUD widgets, including previews of disabled elements"));
        hudEditor.active = minecraft.player != null && minecraft.level != null;
        if (profiles != null) {
            addRenderableWidget(button(layout.left() + layout.width() - 76, layout.top() + 9, 68, 21,
                    () -> "Profiles", () -> false, () -> minecraft.setScreen(new ProfilesScreen(this, profiles, globals, () -> {
                        state.drafts.clear();
                        state.invalidDrafts.clear();
                        save.run();
                    })), "Save and load named local visual configurations"));
        }
        int filterWidth = Math.min(120, layout.width() / 3);
        addRenderableWidget(button(toolbarX, toolbarY, filterWidth, 20,
                () -> layout.narrow() && state.narrowDetails ? "< Modules" : categoryLabel(), () -> false, () -> {
                    if (layout.narrow() && state.narrowDetails) state.narrowDetails = false;
                    else cycleCategory();
                    requestRebuild();
                }, "Filter modules by category. On small windows, this also returns to the module list."));
        int globalWidth = 68;
        int searchX = toolbarX + filterWidth + 6;
        search = new EditBox(font, searchX, toolbarY,
                Math.max(20, layout.width() - filterWidth - globalWidth - 28), 20, Component.literal("Search modules"));
        search.setMaxLength(80);
        search.setHint(Component.literal("Search modules..."));
        search.setValue(state.query);
        search.setResponder(value -> {
            state.query = value;
            state.moduleScroll = 0;
            restoreSearchFocus = true;
            requestRebuild();
        });
        addRenderableWidget(search);
        addRenderableWidget(button(layout.left() + layout.width() - globalWidth - 8, toolbarY, globalWidth, 20,
                () -> "General", () -> state.globalSettings, () -> {
                    state.globalSettings = true;
                    state.narrowDetails = true;
                    state.settingScroll = 0;
                    requestRebuild();
                }, "Global appearance and interface settings"));
        addRenderableWidget(button(layout.left() + layout.width() - 78, layout.footerY(), 70, 19,
                () -> "Done", () -> false, this::onClose, "Save your settings and return to Minecraft"));
        if (layout.categories() != null) buildCategories();
        if (layout.modules() != null) buildModules();
        if (layout.settings() != null) buildSettings();
        if (restoreSearchFocus) {
            setInitialFocus(search);
            search.moveCursorToEnd(false);
            restoreSearchFocus = false;
        }
    }

    private String categoryLabel() { return state.category == null ? "All categories" : state.category.displayName(); }

    private void cycleCategory() {
        Category[] values = Category.values();
        state.category = state.category == null ? values[0]
                : state.category.ordinal() + 1 < values.length ? values[state.category.ordinal() + 1] : null;
        state.moduleScroll = 0;
    }

    private void buildCategories() {
        categoryPane = new ScrollPane(layout.categories(), 0);
        addCategory(null, 5);
        int y = 30;
        for (Category category : Category.values()) { addCategory(category, y); y += 25; }
    }

    private void addCategory(Category category, int y) {
        NexButton button = button(categoryPane.area.x() + 4, 0, categoryPane.area.width() - 8, 21,
                () -> category == null ? "All modules" : category.displayName(), () -> state.category == category,
                () -> { state.category = category; state.moduleScroll = 0; requestRebuild(); }, "Show this module category");
        addWidget(button);
        categoryPane.add(button, y);
    }

    private void buildModules() {
        modulePane = new ScrollPane(layout.modules(), state.moduleScroll);
        List<VisualModule> matching = state.matching(registry);
        if (matching.isEmpty()) {
            modulePane.decorate(14, 25, (graphics, y) -> Draw.text(graphics, font, "No matching modules",
                    modulePane.area.x() + 8, y, 0xFF8896B0, false));
        }
        int y = 5;
        for (VisualModule module : matching) {
            int x = modulePane.area.x() + 5;
            int rowWidth = modulePane.area.width() - 10;
            modulePane.decorate(y, 47, (graphics, rowY) -> {
                Draw.roundedRect(graphics, x, rowY, rowWidth, 47, 4, Draw.withAlpha(0xFF172132, globals.panelOpacity.get().floatValue()));
                Draw.text(graphics, font, module.category().displayName(), x + 7, rowY + 32, 0xFF8796B2, false);
            });
            NexButton select = button(x + 3, 0, rowWidth - 51, 23, module::name,
                    () -> module.id().equals(state.selectedId) && !state.globalSettings, () -> {
                        state.selectedId = module.id();
                        state.globalSettings = false;
                        state.narrowDetails = true;
                        state.settingScroll = 0;
                        requestRebuild();
                    }, module.description());
            addWidget(select);
            modulePane.add(select, y + 3);
            NexButton toggle = button(x + rowWidth - 45, 0, 42, 23, () -> module.enabled() ? "ON" : "OFF",
                    module::enabled, module::toggle, "Enable or disable " + module.name());
            addWidget(toggle);
            modulePane.add(toggle, y + 3);
            y += 53;
        }
    }

    private void buildSettings() {
        settingPane = new ScrollPane(layout.settings(), state.settingScroll);
        VisualModule selected = registry.find(state.selectedId).orElse(null);
        if (selected == null && !state.globalSettings) {
            selected = state.matching(registry).stream().findFirst().orElse(null);
            if (selected != null) state.selectedId = selected.id();
        }
        if (selected == null && !state.globalSettings) {
            settingPane.decorate(12, 30, (graphics, y) -> Draw.text(graphics, font, "Choose a module to customize",
                    settingPane.area.x() + 8, y, 0xFF8896B0, false));
            return;
        }
        VisualModule module = selected;
        String name = state.globalSettings ? "General settings" : module.name();
        List<Setting<?>> settings = state.globalSettings ? globals.settings() : module.settings();
        settingPane.decorate(9, 17, (graphics, y) -> Draw.text(graphics, font,
                font.plainSubstrByWidth(name, settingPane.area.width() - 16), settingPane.area.x() + 8, y, 0xFFE9EDF7, false));
        int x = settingPane.area.x() + 8;
        int controlWidth = (settingPane.area.width() - 22) / 2;
        if (!state.globalSettings) {
            NexButton toggle = button(x, 0, controlWidth, 20, () -> module.enabled() ? "Enabled" : "Disabled",
                    module::enabled, module::toggle, module.description());
            addWidget(toggle);
            settingPane.add(toggle, 27);
        }
        NexButton reset = button(state.globalSettings ? x : x + controlWidth + 6, 0, controlWidth, 20,
                () -> "Reset settings", () -> false, () -> {
                    settings.forEach(setting -> { setting.reset(); state.drafts.remove(setting); state.invalidDrafts.remove(setting); });
                    requestRebuild();
                }, "Restore the settings on this page to their defaults");
        addWidget(reset);
        settingPane.add(reset, 27);
        SettingControls factory = new SettingControls(font, globals, state, this::registerControl,
                setting -> capturing = setting, this::requestRebuild);
        int y = 56;
        if (state.globalSettings && ShaderIntegration.available()) {
            NexButton shaders = button(x, 0, settingPane.area.width() - 16, 20,
                    () -> "Open Iris shader settings", () -> false, () -> ShaderIntegration.openSettings(this),
                    "Open the installed Iris public settings screen. NexVisuals never downloads or chooses shader packs.");
            addWidget(shaders); settingPane.add(shaders, y); y += 24;
        }
        if (!state.globalSettings) {
            if (!module.presets().isEmpty()) {
                int index = presetSelections.getOrDefault(module.id(), 0) % module.presets().size();
                var preset = module.presets().get(index);
                NexButton choose = button(x, 0, settingPane.area.width() - 73, 20,
                        () -> preset.name() + " >", () -> false, () -> {
                            presetSelections.put(module.id(), (index + 1) % module.presets().size()); requestRebuild();
                        }, "Cycle built-in styles. " + preset.description());
                NexButton apply = button(x + settingPane.area.width() - 68, 0, 52, 20,
                        () -> "Apply", () -> false, () -> {
                            module.applyPreset(preset);
                            state.drafts.clear(); state.invalidDrafts.clear(); requestRebuild();
                        }, preset.description());
                addWidget(choose); settingPane.add(choose, y);
                addWidget(apply); settingPane.add(apply, y); y += 24;
            }
            for (var action : module.actions()) {
                NexButton command = button(x, 0, settingPane.area.width() - 16, 20,
                        action::name, () -> false, () -> {
                            action.run().run(); state.drafts.clear(); state.invalidDrafts.clear(); requestRebuild();
                        }, action.description());
                addWidget(command); settingPane.add(command, y); y += 24;
            }
        }
        for (Setting<?> setting : settings) y = factory.add(settingPane, setting, y);
    }

    private void registerControl(AbstractWidget widget) { addWidget(widget); }
    private void requestRebuild() { rebuildRequested = true; }
    private void rememberScroll() {
        if (modulePane != null) state.moduleScroll = modulePane.scroll();
        if (settingPane != null) state.settingScroll = settingPane.scroll();
    }

    private NexButton button(int x, int y, int width, int height, Supplier<String> label,
                             BooleanSupplier selected, Runnable action, String description) {
        NexButton button = new NexButton(x, y, width, height, label, selected, action, globals);
        if (!description.isBlank()) button.setTooltip(Tooltip.create(Component.literal(description)));
        return button;
    }

    @Override public void tick() {
        if (rebuildRequested) {
            rebuildRequested = false;
            rebuildWidgets();
        }
    }

    @Override public void render(GuiGraphics graphics, int mouseX, int mouseY, float delta) {
        Draw.rect(graphics, 0, 0, width, height, 0xB80A0E18);
        Draw.roundedRect(graphics, layout.left(), layout.top(), layout.width(), layout.height(), 8, Draw.withAlpha(0xFF101725, globals.panelOpacity.get().floatValue()));
        Draw.border(graphics, layout.left(), layout.top(), layout.width(), layout.height(), 1, Draw.withAlpha(globals.accentColor.get(), .5f));
        Draw.rect(graphics, layout.left() + 10, layout.top() + 12, 3, 18, globals.accentColor.get());
        Draw.text(graphics, font, "NEXVISUALS", layout.left() + 22, layout.top() + 10, 0xFFF2F5FF, false);
        Draw.text(graphics, font, font.plainSubstrByWidth("Make Minecraft feel like yours", Math.max(20, layout.width() - (profiles == null ? 104 : 178))),
                layout.left() + 22, layout.top() + 24, 0xFF8192B1, false);
        panelBackground(graphics, layout.categories());
        panelBackground(graphics, layout.modules());
        panelBackground(graphics, layout.settings());
        super.render(graphics, mouseX, mouseY, delta);
        if (categoryPane != null) categoryPane.render(graphics, mouseX, mouseY, delta);
        if (modulePane != null) modulePane.render(graphics, mouseX, mouseY, delta);
        if (settingPane != null) settingPane.render(graphics, mouseX, mouseY, delta);
        String status = capturing != null ? "Press a key or mouse button / Esc cancels"
                : state.invalidDrafts.isEmpty() ? "Live preview / saved on close" : "Red input invalid / last valid value kept";
        Draw.text(graphics, font, font.plainSubstrByWidth(status, layout.width() - 100),
                layout.left() + 10, layout.footerY() + 6, capturing == null ? 0xFF8796B2 : globals.accentColor.get(), false);
    }

    @Override public void renderBackground(GuiGraphics graphics, int mouseX, int mouseY, float delta) { }

    private void panelBackground(GuiGraphics graphics, GuiLayout.Rect rect) {
        if (rect != null) Draw.roundedRect(graphics, rect.x(), rect.y(), rect.width(), rect.height(), 5, Draw.withAlpha(0xFF0D1421, globals.panelOpacity.get().floatValue()));
    }

    @Override public boolean mouseScrolled(double mouseX, double mouseY, double horizontal, double vertical) {
        for (ScrollPane pane : new ScrollPane[] { categoryPane, modulePane, settingPane }) {
            if (pane != null && pane.area.contains(mouseX, mouseY)) {
                pane.scrollBy((int) (-vertical * 28));
                rememberScroll();
                return true;
            }
        }
        return super.mouseScrolled(mouseX, mouseY, horizontal, vertical);
    }

    @Override public boolean mouseClicked(MouseButtonEvent event, boolean doubleClick) {
        if (capturing != null) {
            capturing.set(InputConstants.Type.MOUSE.getOrCreate(event.button()).getName());
            capturing = null;
            return true;
        }
        return super.mouseClicked(event, doubleClick);
    }

    @Override public boolean keyPressed(KeyEvent event) {
        if (capturing != null) {
            if (event.key() == GLFW.GLFW_KEY_UNKNOWN) return true;
            if (event.key() != GLFW.GLFW_KEY_ESCAPE) capturing.set(InputConstants.getKey(event).getName());
            capturing = null;
            return true;
        }
        if (event.key() == GLFW.GLFW_KEY_F && (event.modifiers() & GLFW.GLFW_MOD_CONTROL) != 0) {
            setFocused(search);
            return true;
        }
        if (event.key() == GLFW.GLFW_KEY_PAGE_DOWN || event.key() == GLFW.GLFW_KEY_PAGE_UP) {
            ScrollPane pane = settingPane != null ? settingPane : modulePane;
            if (pane != null) pane.scrollBy((event.key() == GLFW.GLFW_KEY_PAGE_DOWN ? 1 : -1) * Math.max(28, pane.area.height() - 25));
            rememberScroll();
            return true;
        }
        boolean handled = super.keyPressed(event);
        if (categoryPane != null) categoryPane.revealFocused();
        if (modulePane != null) modulePane.revealFocused();
        if (settingPane != null) settingPane.revealFocused();
        rememberScroll();
        return handled;
    }

    @Override public void resize(int width, int height) { rememberScroll(); super.resize(width, height); }
    public void selectModule(String id) {
        state.selectedId = id;
        registry.find(id).ifPresent(module -> state.category = module.category());
        state.query = "";
        state.globalSettings = false;
        state.narrowDetails = true;
        state.settingScroll = 0;
    }
    @Override public void onClose() { minecraft.setScreen(parent); }
    @Override public void removed() { state.remember(globals); save.run(); }
    @Override public boolean isPauseScreen() { return false; }
}
